### ISSUE TITLE
Range in Miles no longer shows - Just KM

### ISSUE THREAD

**Issue by dward32** [mitch-dc/volkswagen_we_connect_id#135]
We used to have range in Miles but that seems to not be available as an option, Just KM.. Please can we have miles again. Thanks

**Comment by dward32** [comment]
Is this possible please? Thanks

**Comment by dward32** [comment]
hello!?

**Comment by mitch-dc** [comment]
Sorry, you can add the sensor yourself by using a template sensor.

**Comment by olirogers** [comment]
I added this to my configuration.yaml:

```
template:
  - sensor:
      - name: "Range (Miles)"
        unique_id: "car_range_miles"
        unit_of_measurement: "Miles"
        icon: "mdi:car-arrow-right"
        state: "{{ states('sensor.car_range')|float * 0.621371 }}"

      - name: "Charge Rate (Miles/h)"
        unique_id: "car_charge_rate_miles"
        unit_of_measurement: "Miles/h"
        icon: "mdi:speedometer"
        state: "{{ states('sensor.car_charge_rate')|float * 0.621371 }}"
```

Replace the sensor.car_* with whatever you named your entity when you connected the integration.

I've just installed the integration so don't know if these are the only two based on KM.
It would be nice if these were provided sensors though.
