### ISSUE TITLE
Add Reduce Charge Power, unlock Cable and Start/Stop Charging Buttons

### ISSUE THREAD

**Issue by Schnabel80** [mitch-dc/volkswagen_we_connect_id#160]
Thanks for your Work

**Comment by Seb2ag** [comment]
I have the start/stop buttons. (Had to reinstall)

I also have a request :
My car forget to switch to "charge at preferred time" when the car is home. Instead it stays in the "charge immediatly" mode.
Is there a way to switch between the two charge mode when at home ?

Also thank you for your work

**Comment by roppenheimer** [comment]
Is there a way to set the charging power to “maximum” or “reduced” as opposed to just toggling them?

**Comment by mitch-dc** [comment]
```
service: volkswagen_we_connect_id.volkswagen_id_set_ac_charge_speed
data:
  vin: WVGZZZA1ZMP001337
  maximum_reduced: maximum
```
