### ISSUE TITLE
Expose "Reduced AC charging current" setting as control/switch

### ISSUE THREAD

**Issue by FirstRulez** [mitch-dc/volkswagen_we_connect_id#184]
**Is your feature request related to a problem? Please describe.**
I would like to be able to control the setting "Reduced AC charging current" on my ID.4 so that when charging at home during the day my charge rate is lower than my solar generation capacity meaning I do not use expensive grid energy.

**Describe the solution you'd like**
An additional control/configuration entity exposed as an on/off switch to control this setting on my car.

**Describe alternatives you've considered**
Any other controls which the API exposes allowing me to limit the charge rate of the vehicle, particularly one I can control from an HA automation would be helpful and resolve my request.

**Additional context**
I do not have a smart car charger which can be used to control the rate of charge so am looking to use the capability of the vehicle instead. This setting is exposed by the VW mobile app and works when used on my vehicle. Note my car is currently on v2.4 so ideally would like something which works for all vehicle software versions from 2.4 upwards.

**Comment by GrmpfNarf** [comment]
Hi,
this is already possible as a service.
![Uploading IMG_1714.jpeg…]()

**Comment by GrmpfNarf** [comment]
Hi,
this is already possible as a service.
![IMG_1714](https://github.com/mitch-dc/volkswagen_we_connect_id/assets/23635882/385bd791-0655-4c27-b3c6-c7b1e7e02a0c)

**Comment by GrmpfNarf** [comment]
Hi,
there is a Button for that. But it is a button not a switch. The Button toggles the "AC Charging Speed". If you want to get a switch you can put this into you ``configuration.yaml``.
```yaml
switch:
  - platform: template
    switches:
      reduced_ac_speed:
        friendly_name: "Reduce AC Speed"
        unique_id: "d6634f16-0eeb-4b0b-8c17-46b78b177d94"
        icon_template: "mdi:ev-station"
        value_template: "{{ is_state('sensor.id_4_pro_performance_150_kw_204_ps_max_charge_current_ac', 'reduced') }}"
        turn_on:
          service: button.press 
          target:
            entity_id: "button.id_4_pro_performance_150_kw_204_ps_toggle_ac_charge_speed"
        turn_off:
          service: button.press
          target:
            entity_id: "button.id_4_pro_performance_150_kw_204_ps_toggle_ac_charge_speed"
```

The problem with the switch is that he shows the state of a variable. When the variable is not changed within a certain amount of time after pressing the switch the switch returns to the previous state. It takes several minutes that the state is changed after pressing the toggle button because it's a asynchronous event. 
So when the switch is pressed it returns to the previous state after some seconds and, when the variable is changed, it switches to the expected state. I think that's the main reason why it isn't a switch for now. 

<img width="406" alt="Bildschirm­foto 2023-06-18 um 13 54 43" src="https://github.com/mitch-dc/volkswagen_we_connect_id/assets/23635882/0d7dfa8f-47e9-4998-a77a-721f2e24021a">
![ezgif-2-5308fc6f18](https://github.com/mitch-dc/volkswagen_we_connect_id/assets/23635882/2081a2a0-07d0-417d-a4ca-bf949af7a77b)

**Comment by mitch-dc** [comment]
> Hi,
> 
> there is a Button for that. But it is a button not a switch. The Button toggles the "AC Charging Speed". If you want to get a switch you can put this into your ``configuration.yaml``.
> 
> ```yaml
> 
> switch:
> 
>   - platform: template
> 
>     switches:
> 
>       reduced_ac_speed:
> 
>         friendly_name: "Reduce AC Speed"
> 
>         unique_id: "d6634f16-0eeb-4b0b-8c17-46b78b177d94"
> 
>         icon_template: "mdi:ev-station"
> 
>         value_template: "{{ is_state('sensor.id_4_pro_performance_150_kw_204_ps_max_charge_current_ac', 'reduced') }}"
> 
>         turn_on:
> 
>           service: button.press 
> 
>           target:
> 
>             entity_id: "button.id_4_pro_performance_150_kw_204_ps_toggle_ac_charge_speed"
> 
>         turn_off:
> 
>           service: button.press
> 
>           target:
> 
>             entity_id: "button.id_4_pro_performance_150_kw_204_ps_toggle_ac_charge_speed"
> 
> ```
> 
> 
> 
> The problem with the switch is that he shows the state of a variable. When the variable is not changed within a certain amount of time after pressing the switch the switch returns to the previous state. It takes several minutes that the state is changed after pressing the toggle button because it's an asynchronous event. 
> 
> So when the switch is pressed it returns to the previous state after some seconds and, when the variable is changed, it switches to the expected state. I think that's the main reason why it isn't a switch for now. 
> 
> 
> 
> <img width="406" alt="Bildschirm­foto 2023-06-18 um 13 54 43" src="https://github.com/mitch-dc/volkswagen_we_connect_id/assets/23635882/0d7dfa8f-47e9-4998-a77a-721f2e24021a">
> 
> 
> 
> ![ezgif-2-5308fc6f18](https://github.com/mitch-dc/volkswagen_we_connect_id/assets/23635882/d9f9a246-cdaf-4eee-8b56-e5ba478ea251)
> 
> 
> 
> 

You are right. The api is so slow that switches are just not working how we should want it. 

Its annoying but in my case the buttons work fine :)

**Comment by FirstRulez** [comment]
Thank you both for the extra info - I do not see those buttons. Do I need to to something specific to get them to show?
I have v0.1.6 installed via HACS at the moment (just about to update to v0.1.7)

**Comment by mitch-dc** [comment]
```
type: entities
entities:
  - entity: button.komo_start_climate
    name: Start Climate
    icon: ''
    secondary_info: last-updated
  - entity: button.komo_stop_climate
    secondary_info: last-changed
    name: Stop Climate
  - entity: button.komo_toggle_ac_charge_speed
    name: Toggle Charge Speed
    secondary_info: last-changed
    icon: mdi:tortoise
title: Komo Actions
```

Your entities will have a different name based on the nickname of your car (mine is Komo). 
![image](https://github.com/mitch-dc/volkswagen_we_connect_id/assets/15835274/84c19728-6892-4b31-8160-43708922efed)
