### ISSUE TITLE
Long Term Statistics

### ISSUE THREAD

**Issue by ColinRobbins** [mitch-dc/volkswagen_we_connect_id#43]
**Is your feature request related to a problem? Please describe.**
Cannot use sensor data in long term statistics graphs.

**Describe the solution you'd like**
Add a `state class` to sensor entities, so the are available for use as [long term statistics](https://developers.home-assistant.io/docs/core/entity/sensor/).

**Describe alternatives you've considered**
Emulating it locally with template sensors works.
```
template:
  sensor: 
    - name: EV Range Stat
      unique_id: 1234
      unit_of_measurement: 'miles'
      state: "{{ states('sensor.ev_range_in_miles') }} "
      state_class: measurement
      icon: 'mdi:map-marker-distance'
```

**Additional context**
Happy to be a tester.
