### ISSUE TITLE
When setting number.target_state_of_charge we charge app crashes

### ISSUE THREAD

**Issue by gluca** [mitch-dc/volkswagen_we_connect_id#64]
## Version of the custom_component
latest (0.0.13?)

## Installation method (hacs / manual)
hacs

## Installation method of hass (venv, docker, hassio,...)
docker-compose

## Configuration

no need to add configuration.yaml because integration works as expected but cause we charge to crash 

## Describe the bug

If from HA we set target state of charge to a value different from 0,10,20,30,40,50,60,70,80,90,100, then when I try to get into settings from we charge app, we charge app crashes. GUI in HA should reflect slide steps as per we charge app (in 10 increments)

No log and configuration provided because the HA component works as designed (it sends the right target state to the car).

**Comment by DarkFox** [comment]
Climate temperature need the following attributes set:
```
  step: 0.5
  min: 15
  max: 30
```
In addition, charging target needs these:
```
  step: 10
  min: 50
  max: 100
```

As a temporary workaround, you can do this by customizing your entites, as described here: https://www.home-assistant.io/docs/configuration/customizing-devices/#manual-customization

Mine is like this:
```
homeassistant:
  customize:
    number.id3_target_climate_temperature:
      step: 0.5
      min: 15
      max: 30
    number.id3_target_state_of_charge:
      step: 10
      min: 50
      max: 100

```
