### ISSUE TITLE
Config flow could not be loaded: undefined

### ISSUE THREAD

**Issue by nikkilocke** [mitch-dc/volkswagen_we_connect_id#67]
## Version of the custom_component
v0.0.13

## Installation method (hacs / manual)
HACS

## Installation method of hass (venv, docker, hassio,...)
Docker

## Configuration

```yaml


# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
homeassistant:
  packages: !include_dir_named packages


```

## Describe the bug

Attempting to install the integration in Home Assistant gives a twirly wait icon for a while, then I get the message "Config flow could not be loaded: undefined"

## Debug log
```text
[Attached](url)
```
[homeassistant.txt](https://github.com/mitch-dc/volkswagen_we_connect_id/files/9626012/homeassistant.txt)
